version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dQdw@6]uazY9Y>DBX.
      POSTGRES_DB: onboarding-db